export const productsListing = [
  {
    field: 'id',
    headerName: 'ID',
    width: 100,
    type: ['options', 'id'],
    floatingFilter: true,
    enableRowGroup: false,
    sortable: true,
  },
  {
    field: 'codigo',
    headerName: 'Código',
    width: 150,
    type: 'text',
    floatingFilter: true,
    enableRowGroup: false,
  },
  {
    field: 'nombre_descripcion',
    headerName: 'Descripción',
    width: 600,
    type: 'text',
    enableRowGroup: false,
  },
  {
    field: 'precio_eur',
    headerName: 'PVP',
    width: 120,
    type: ['price', 'text'],
    enableRowGroup: true,
  },
  {
    field: 'articuloAlmacen.stock_total',
    headerName: 'Stock',
    width: 100,
    type: 'stock',
    enableRowGroup: true,
    sortable: true,
  },
  {
    field: 'laboratorio.nombre',
    headerName: 'Fabricante',
    width: 300,
    type: 'text',
    enableRowGroup: true,
  },
  {
    field: 'tipo',
    headerName: 'Tipo',
    width: 300,
    type: 'text',
    enableRowGroup: true,
  },
  // {
  //   field: 'proveedor_predeterminado',
  //   headerName: 'Proveedor',
  //   width: 300,
  //   type: 'text',
  // },
]
