export const recipeBookHistory = [
  {
    field: 'numRecetario',
    headerName: 'NºRecetario',
    width: 200,
    type: 'checkbox',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'codigo',
    headerName: 'Código',
    width: 200,
    type: 'number',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'descripcion',
    headerName: 'Descripción',
    width: 400,
    type: 'text',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'fechaDispensacion',
    headerName: 'Fecha dispensación',
    width: 400,
    type: 'text',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'medico',
    headerName: 'Médico',
    width: 400,
    type: 'text',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'numRecetario',
    headerName: 'NºRecetario',
    width: 400,
    type: 'text',
    floatingFilter: true,
    sortable: true,
  },
  {
    field: 'paciente',
    headerName: 'Paciente',
    width: 400,
    type: 'text',
    floatingFilter: true,
    sortable: true,
  },
]
