export const tpv = [
  {
    id: 0,
    field: 'id',
    headerName: 'ID',
    width: 70,
    type: 'first',
    floatingFilter: false,
  },
  {
    field: 'codigo',
    headerName: 'Código',
    width: 100,
    type: 'numericColumn',
    floatingFilter: false,
    editable: (params) => !(params.data && params.data.id),
  },
  {
    field: 'paciente.nombre',
    headerName: 'Paciente',
    width: 180,
    // type: 'text',
    editable: (params) => params.data && params.data.id && params.data.paciente,
    cellEditor: 'cellSearch',
    cellStyle: { overflow: 'visible' },
  },
  {
    field: 'articulo.nombre_descripcion',
    headerName: 'Artículo',
    width: 300,
    type: 'text',
  },
  {
    field: 'unidades',
    headerName: 'Unidades',
    width: 120,
    type: 'number',
    editable: (params) => !!(params.data && params.data.id),
  },
  {
    field: 'importe_pvp',
    headerName: 'PVP',
    width: 180,
    type: ['number', 'price'],
  },
  {
    field: 'importe_dto_porcentaje',
    headerName: 'Descuento %',
    width: 180,
    type: ['number', 'porcentage'],
    editable: (params) => !!(params.data && params.data.id),
  },
  {
    field: 'importe_dto_directo',
    headerName: 'Descuento directo',
    width: 180,
    type: ['number', 'price'],
    editable: (params) => !!(params.data && params.data.id),
  },
  {
    field: 'importe_a_pagar',
    headerName: 'Total',
    width: 100,
    type: ['number', 'price'],
  },
  {
    field: 'articulo.stock',
    headerName: 'Stock',
    width: 100,
    type: 'stock',
  },
]
