export const warehouse = [
  {
    field: 'id',
    headerName: 'ID',
    width: 100,
    type: ['first', 'id'],
    floatingFilter: true,
    enableRowGroup: false,
    sortable: true,
  },
  {
    field: 'ubicacion',
    headerName: 'Ubicaciones',
    width: 300,
    type: 'text',
    floatingFilter: true,
    rowGroup: true,
    enableRowGroup: true,
    hide: false,
  },
  {
    field: 'fechaCompra',
    headerName: 'Fecha de compra',
    width: 300,
    type: 'text',
    floatingFilter: true,
  },
  {
    field: 'caducidad',
    headerName: 'Caducidad',
    width: 180,
    type: 'text',
    floatingFilter: true,
  },
  {
    field: 'numLote',
    headerName: 'Nº Lote',
    width: 180,
    type: 'text',
    floatingFilter: true,
  },
  {
    field: 'numSerie',
    headerName: 'Nº Serie',
    width: 180,
    type: 'text',
    floatingFilter: true,
  },
]
