export const RESTORE_SETTINGS = 'RESTORE_SETTINGS'
export const RESTORE_SETTINGS_SUCCESS = 'RESTORE_SETTINGS_SUCCESS'
export const RESTORE_SETTINGS_FAILED = 'RESTORE_SETTINGS_FAILED'

export const UPDATE_SETTING = 'UPDATE_SETTING'
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS'
export const UPDATE_SETTING_FAILED = 'UPDATE_SETTING_SUCCESS'

export const RESTORE_FILTERS = 'RESTORE_FILTERS'
export const RESTORE_FILTERS_SUCCESS = 'RESTORE_FILTERS_SUCCESS'
export const RESTORE_FILTERS_FAILED = 'RESTORE_FILTERS_FAILED'

export const SAVE_FILTER = 'SAVE_FILTER'
export const SAVE_FILTER_SUCCESS = 'SAVE_FILTER_SUCCESS'
export const SAVE_FILTER_FAILED = 'SAVE_FILTER_FAILED'

export const DELETE_FILTER = 'DELETE_FILTER'
export const DELETE_FILTER_SUCCESS = 'DELETE_FILTER_SUCCESS'
export const DELETE_FILTER_FAILED = 'DELETE_FILTER_FAILED'

export const CLEAN_AGGRID = 'CLEAN_AGGRID'

export const CURRENT_USER_PERMISSIONS = 'CURRENT_USER_PERMISSIONS'
