export const SET_COUNTER_DESK = 'SET_COUNTER_DESK'
export const SET_COUNTER_DESK_SUCCESS = 'SET_COUNTER_DESK_SUCCESS'
export const SET_COUNTER_DESK_FAIL = 'SET_COUNTER_DESK_FAIL'

export const CHECK_OPEN_CASH = 'CHECK_OPEN_CASH'
export const CHECK_OPEN_CASH_SUCCESS = 'CHECK_OPEN_CASH_SUCCESS'
export const CHECK_OPEN_CASH_FAILED = 'CHECK_OPEN_CASH_FAILED'
