export const ADD_EMPLOYEES = 'ADD_EMPLOYEES'
export const ADD_EMPLOYEES_SUCCESS = 'ADD_EMPLOYEES_SUCCESS'
export const ADD_EMPLOYEES_FAILED = 'ADD_EMPLOYEES_FAILED'

export const OPEN_MODAL_EMPLOYEE = 'OPEN_MODAL_EMPLOYEE'
export const OPEN_MODAL_EMPLOYEE_SUCCESS = 'OPEN_MODAL_EMPLOYEE_SUCCESS'
export const OPEN_MODAL_EMPLOYEE_FAILED = 'OPEN_MODAL_EMPLOYEE_FAILED'
