export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS'
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED'
export const CLEAN_FAVORITES = 'CLEAN_FAVORITES'
