export const SELECT_MENU_ITEM = 'SELECT_MENU_ITEM'
export const SELECT_MENU = 'SELECT_MENU'
export const BACK_TO_MENU = 'BACK_TO_MENU'
export const OPEN_MENU = 'OPEN_MENU'
export const OPEN_MENU_FAILED = 'OPEN_MENU_FAILED'
export const UPDATE_MENU = 'UPDATE_MENU'
export const UPDATE_FAVS = 'UPDATE_FAVS'
export const SEARCH_DATA = 'SEARCH_DATA'

export const GET_MENU = 'GET_MENU'
export const GET_MENU_SUCCES = 'GET_MENU_SUCCES'
export const GET_MENU_FAILED = 'GET_MENU_FAILED'

export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_FAVORITES_SUCCES = 'GET_FAVORITES_SUCCES'
export const GET_FAVORITES_FAILED = 'GET_FAVORITES_FAILED'

export const ADD_FAVORITES = 'ADD_FAVORITES'
export const ADD_FAVORITES_SUCCES = 'ADD_FAVORITES_SUCCES'
export const ADD_FAVORITES_FAILED = 'ADD_FAVORITES_FAILED'

export const DEL_FAVORITES = 'DEL_FAVORITES_MENU'
export const DEL_FAVORITES_SUCCES = 'DEL_FAVORITES_SUCCES'
export const DEL_FAVORITES_FAILED = 'DEL_FAVORITES_FAILED'

export const SEARCH_MENU = 'SEARCH_MENU'
export const SEARCH_LOADING_RESOURCES = 'SEARCH_LOADING_RESOURCES'
export const SEARCH_LOADING_RESOURCES_SUCCESS =
  'SEARCH_LOADING_RESOURCES_SUCCESS'
export const SEARCH_LOADING_RESOURCES_FAILED = 'SEARCH_LOADING_RESOURCES_FAILED'
export const SEARCH_MENU_SUCCESS = 'SEARCH_MENU_SUCCESS'
export const SEARCH_MENU_FAILED = 'SEARCH_MENU_FAILED'
