export const MULTIUSER_CHANGE_USER = 'MULTIUSER_CHANGE_USER'
export const MULTIUSER_CHANGE_USER_SUCCESS = 'MULTIUSER_CHANGE_USER_SUCCESS'
export const MULTIUSER_CHANGE_USER_FAILED = 'MULTIUSER_CHANGE_USER_FAILED'

export const MULTIUSER_ADD_USER = 'MULTIUSER_ADD_USER'
export const MULTIUSER_ADD_USER_SUCCESS = 'MULTIUSER_ADD_USER_SUCCESS'
export const MULTIUSER_ADD_USER_FAILED = 'MULTIUSER_ADD_USER_FAILED'

export const MULTIUSER_UPDATE = 'MULTIUSER_UPDATE'
export const MULTIUSER_UPDATE_SUCCESS = 'MULTIUSER_UPDATE_SUCCESS'
export const MULTIUSER_UPDATE_FAILED = 'MULTIUSER_UPDATE_FAILED '

export const MULTIUSER_REMOVE_USER = 'MULTIUSER_REMOVE_USER'
export const MULTIUSER_REMOVE_USER_SUCCESS = 'MULTIUSER_REMOVE_USER_SUCCESS'
export const MULTIUSER_REMOVE_USER_FAILED = 'MULTIUSER_REMOVE_USER_FAILED'
