export const NAVIGATION_PUSH = 'NAVIGATION_PUSH'
export const NAVIGATION_PUSH_SUCCESS = 'NAVIGATION_PUSH_SUCCESS'
export const NAVIGATION_PUSH_FAILED = 'NAVIGATION_PUSH_FAILED'

export const NAVIGATION_DELETE = 'NAIGATION_DELETE'
export const NAVIGATION_TOGGLE = 'NAVIGATION_TOGGLE'

export const SET_SESSION = 'SET_SESSION'
export const SET_SESSION_SUCCESS = 'SET_SESSION_SUCCESS'
export const SET_SESSION_FAILED = 'SET_SESSION_FAILED'

export const CLEAN_NAVIGATION = 'CLEAN_NAVIGATION'
