export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS'
export const CREATE_CART_FAILED = 'CREATE_CART_FAILED'
export const CREATE_CART = 'CREATE_CART'

export const CREATE_NEW_CART = 'CREATE_NEW_CART'
export const CREATE_NEW_CART_SUCCESS = 'CREATE_NEW_CART_SUCCESS'
export const CREATE_NEW_CART_FAILED = 'CREATE_NEW_CART_FAILED'

export const DELETE_LINE = 'DELETE_LINE'
export const DELETE_LINE_SUCCESS = 'DELETE_LINE_SUCCESS'
export const DELETE_LINE_FAILED = 'DELETE_LINE_FAILED'

export const SET_CLIENT_TPV = 'SET_CLIENT_TPV'
export const SET_CLIENT_TPV_SUCCESS = 'SET_CLIENT_TPV_SUCCESS'
export const SET_CLIENT_TPV_FAILED = 'SET_CLIENT_TPV_FAILED'

export const SET_MODAL_ERECETA = 'SET_MODAL_ERECETA'
export const SET_ERECETA_CODE = 'SET_ERECETA_CODE'

export const SET_CASHDESK = 'SET_CASHDESK'

export const SET_CLIENT_BALANCE = 'SET_CLIENT_BALANCE'
