export const SELECT_SOFTWARE = 'SELECT_SOFTWARE'
export const SELECT_SOFTWARE_SUCCESS = 'SELECT_SOFTWARE_SUCCESS'
export const SELECT_SOFTWARE_FAILED = 'SELECT_SOFTWARE_FAILED'

export const OPEN_SELECT_SOFTWARE = 'OPEN_SELECT_SOFTWARE'
export const OPEN_SELECT_SOFTWARE_SUCCESS = 'OPEN_SELECT_SOFTWARE_SUCCESS'
export const OPEN_SELECT_SOFTWARE_FAILED = 'OPEN_SELECT_SOFTWARE_FAILED'

export const SET_SOFTWARES = 'SET_SOFTWARES'
export const SET_SOFTWARES_SUCCESS = 'SET_SOFTWARES_SUCCESS'
export const SET_SOFTWARES_FAILED = 'SET_SOFTWARES_FAILED'

export const SEARCH_RESOURCES = 'SEARCH_RESOURCES'
export const SEARCH_RESOURCES_SUCCESS = 'SEARCH_RESOURCES_SUCCESS'
export const SEARCH_RESOURCES_FAILED = 'SEARCH_RESOURCES_FAILED'

export const CLEAN_SOFTWARE = 'CLEAN_SOFTWARE'
