export const SET_TOKEN = 'SET_TOKEN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_WAREHOUSES_SUCCESS = 'UPDATE_WAREHOUSES_SUCCESS'
export const UPDATE_WAREHOUSES_FAILED = 'UPDATE_WAREHOUSES_FAILED'
export const UPDATE_WAREHOUSES = 'UPDATE_WAREHOUSES'

export const TURN_SESSION = 'TURN_SESSION'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const UPDATE_PHARACY = 'UPDATE_PHARACY'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'
