export const GET_WAREHOUSES = 'GET_WAREHOUSES'
export const GET_WAREHOUSES_SUCCESS = 'GET_WAREHOUSES_SUCCESS'
export const GET_WAREHOUSES_FAILED = 'GET_WAREHOUSES_FAILED'

export const SET_WAREHOUSE = 'SET_WAREHOUSE'
export const SET_WAREHOUSE_SUCCESS = 'SET_WAREHOUSE_SUCCESS'
export const SET_WAREHOUSE_FAILED = 'SET_WAREHOUSE_FAILED'
