export const SET_WORKSTATION = 'SET_WORKSTATION'
export const SET_WORKSTATION_SUCCESS = 'SET_WORKSTATION_SUCCESS'
export const SET_WORKSTATION_FAILED = 'SET_WORKSTATION_FAILED'

export const CLOSE_WORKSTATION = 'CLOSE_WORKSTATION'
export const CLOSE_WORKSTATION_SUCCESS = 'CLOSE_WORKSTATION_SUCCESS'
export const CLOSE_WORKSTATION_FAILED = 'CLOSE_WORKSTATION_FAILED'

export const OPEN_WORKSTATION = 'OPEN_WORKSTATION'
export const OPEN_WORKSTATION_SUCCESS = 'OPEN_WORKSTATION_SUCCESS'
export const OPEN_WORKSTATION_FAILED = 'OPEN_WORKSTATION_FAILED'
