export const pharmacy = `
    id
    nombre
    id_sertec
    email
    paleta{
        id
        nombre
        primario
        secundario
        terciario
    }
    grupos{
        id
        nombre
        logo
        paleta{
            id
            nombre
            primario
            secundario
            terciario
        }
    }
    grupoCorporativo{
        id
        nombre
        logo
        paleta{
            id
            nombre
            primario
            secundario
            terciario
        }
    }
    logotipo{
        url
        url_250
        url_miniatura
    }
`
